version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: chrislovenes-8080.theiaopenshiftnext-0-labs-prod-theiaopenshift-4-tor01.proxy.cognitiveclass.ai
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_ADDRESS_FORWARDING: "true"  # Changement clé
      KC_HTTP_ENABLED: "true"
      KC_SPI_THEME_WELCOME_THEME_CACHE_TEMPLATES: "false"
      KC_SPI_THEME_WELCOME_THEME_CACHE_THEME: "false"
      KC_SPI_THEME_LOGIN_THEME_CACHE_TEMPLATES: "false"
      KC_SPI_THEME_LOGIN_THEME_CACHE_THEME: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./themes:/opt/keycloak/themes
    command: start-dev --proxy-headers=xforwarded --hostname-strict=false